version: '3.8'

# ประกาศรายชื่อลูกน้อง (Services) ที่เรามี
services:
  # 1. ลูกน้องคนที่ 1: API (Backend)
  api:
    build: ./api # บอกผู้จัดการว่าสูตรทำกล่องอยู่ที่โฟลเดอร์ api นะ
    ports:
      - "3000:3000" # ถ้ามีคนเข้าพอร์ต 3000 ของเครื่องเรา ให้ส่งไปที่พอร์ต 3000 ของกล่องนี้
    restart: always # ถ้ากล่องพังหรือรีสตาร์ทเครื่อง ให้มันเปิดตัวเองขึ้นมาใหม่เสมอ

  # 2. ลูกน้องคนที่ 2: Backoffice (ระบบหลังบ้าน)
  backoffice:
    build: ./backoffice/app # สูตรอยู่ที่นี่
    ports:
      - "3002:80" # ถ้ามีคนเข้าพอร์ต 3002 ของเครื่องเรา ให้ส่งไปที่พอร์ต 80 (พอร์ตของ Nginx) ในกล่อง
    restart: always

  # 3. ลูกน้องคนที่ 3: Web (หน้าเว็บลูกค้า)
  web:
    build: ./web/app # สูตรอยู่ที่นี่
    ports:
      - "3001:80" # ถ้ามีคนเข้าพอร์ต 3001 ของเครื่องเรา ให้ส่งไปที่พอร์ต 80 ในกล่อง
    restart: always