version: '3.8'

services:
  # --- เพิ่ม Database เข้าไปตรงนี้ครับ ---
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 # เปลี่ยนให้ตรงกับที่ตั้งในโค้ด API นะครับ
      POSTGRES_DB: db_workshop_pos
    ports:
      - "5432:5432"

  # 1. ลูกน้องคนที่ 1: API (Backend)
  api:
    build: ./api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db # บอก API ว่าต้องรอให้ db รันขึ้นมาก่อนนะ

  # 2. ลูกน้องคนที่ 2: Backoffice
  backoffice:
    build: ./backoffice/app
    ports:
      - "3002:80"
    restart: always

  # 3. ลูกน้องคนที่ 3: Web
  web:
    build: ./web/app
    ports:
      - "3001:80"
    restart: always